version: 0.2

phases:
  build:
    commands:
      - sam build -t template.yaml

  post_build:
    commands:
      - |
        sam deploy --config-env Staging --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM --guided
        